### ISSUE TITLE
Ajuste da URL de imagens

### ISSUE THREAD

**Issue by PedroAntunesCosta** [vtexdocs/helpcenter#84]
O conteúdo dos artigos referencia as imagens pela URL da hospedagem no contentful. Após migrar as imagens para o Github ([issue 83](https://github.com/vtexdocs/helpcenter/issues/83)), devemos garantir que todos os artigos contém as novas URLs do Github.

O ideal é que isso seja parte da action do repo help-center-content que puxa o conteúdo dos artigos do Contentful.
- [Action](https://github.com/vtexdocs/help-center-content/actions/workflows/retrieve-docs.yml)
- [Script](https://github.com/vtexdocs/help-center-content/blob/main/index.js)

**Comment by julia-rabello** [comment]
There's already a script run by an action, but it fails on most pull requests due to the lack of image compression.

Example:

```yaml
remote: warning: File images/pt/importacao-de-pedidos-amazon-dba-0.gif is 53.15 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
remote: error: Trace: 26f7634c1754cb5122bf0bcd2d0132c8fdcb27c3226ac5dbda08c6671720663f        
remote: error: See https://gh.io/lfs for more information.        
remote: error: File images/pt/skus-recebidos-beta-0.gif is 222.32 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: File images/en/offer-status-0.gif is 207.82 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: File images/es/modulo-status-de-los-anuncios-para-integraciones-con-marketplaces-vtex-0.gif is 225.69 MB; this exceeds GitHub's file size limit of 100.00 MB        
remote: error: File images/pt/modulo-status-dos-anuncios-para-integracoes-com-marketplaces-vtex-0.gif is 227.28 MB; this exceeds GitHub's file size limit of 100.00 MB
```
